from collections import defaultdict
from typing import List

from utils.input_reader import read_file


def format_data(raw_data: str) -> List[int]:
    secrets = []
    for line in raw_data.split("\n"):
        secrets.append(int(line.strip()))
    return secrets


def next_secret(secret: int) -> int:
    secret ^= secret * 64
    secret %= 16777216
    secret ^= secret // 32
    secret %= 16777216
    secret ^= secret * 2048
    secret %= 16777216
    return secret


def sum_secrets(raw_input: str, iteration: int) -> int:
    buyers_secrets = format_data(raw_input)
    for i, s in enumerate(buyers_secrets):
        seed = s
        for j in range(iteration):
            output = next_secret(seed)
            seed = output
        buyers_secrets[i] = seed

    return sum(buyers_secrets)


def most_bananas(raw_input: str, iteration: int) -> int:
    buyers_secrets = format_data(raw_input)
    secrets = defaultdict(dict)
    for s in buyers_secrets:
        seed = s
        secrets[s] = {
            "sequences": [seed],
            "prices": [int(str(seed)[-1])],
            "changes": [0]
        }

        before = secrets[s]["prices"][0]
        for j in range(iteration):
            output = next_secret(seed)
            seed = output
            price = int(str(seed)[-1])
            secrets[s]["sequences"].append(seed)
            secrets[s]["prices"].append(price)
            secrets[s]["changes"].append(price - before)
            before = price

    # sliding window
    window = defaultdict(dict)
    for s in secrets:
        for i in range(1, len(secrets[s]["changes"]) - 4):
            sequence = tuple(secrets[s]["changes"][i:i + 4])
            if s not in window[sequence]:
                window[sequence][s] = secrets[s]["prices"][i + 3]

    max_value = float('-inf')
    for w in window:
        s = sum(window[w].values())
        max_value = max(max_value, s)
    return max_value


if __name__ == "__main__":
    file = read_file("inputs/input.txt")
    print(f"Sum of the 2000th secret number generated by each buyer: {sum_secrets(file, iteration=2000)}")
    print(f"Most bananas: {most_bananas(file, iteration=2000)}")
