from typing import List


def read_file(input_file_path: str) -> str:
    with open(input_file_path) as input_file:
        return input_file.read()


def format_data(raw_data: str) -> List[str]:
    codes = []
    for line in raw_data.split("\n"):
        codes.append(line.strip())
    return codes


def next_secret(secret: int) -> int:
    secret ^= secret * 64
    secret %= 16777216
    secret ^= secret // 32
    secret %= 16777216
    secret ^= secret * 2048
    secret %= 16777216
    return secret


def sum_secrets(raw_input: str, iteration: int) -> int:
    return 0


if __name__ == "__main__":
    file = read_file("inputs/input.txt")
    print(f"Sum of the 2000th secret number generated by each buyer: {sum_secrets(file, iteration=2000)}")
